name: Build Windows App

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx prisma generate
      - run: npm run build
      - run: npm run dist:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: Duty-Scheduler-Windows
          path: |
            dist/*.exe
            dist/*.blockmap
